package org.one.patientmanagement.ui.components;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public final class AttachmentRow extends javax.swing.JPanel {

    /**
     * Creates new form PrescriptionRow
     */
    public AttachmentRow() {
        initComponents();
    }

    public void setPrescriptionData(String fileName, LocalDateTime date) {
        this.fileName.setText(fileName);
        dateLabel.setText(
                date
                        .toLocalDate()
                        .format(DateTimeFormatter.ofPattern("MM/dd/yyyy"))
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fileName = new javax.swing.JLabel();
        datePanel = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.GridBagLayout());

        fileName.setFont(new java.awt.Font("Manrope Medium", 0, 13)); // NOI18N
        fileName.setText("Amoxicilin 400mg");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 6, 0);
        add(fileName, gridBagConstraints);

        datePanel.setBackground(new java.awt.Color(255, 240, 244));
        datePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        datePanel.setMaximumSize(new java.awt.Dimension(32767, 16));
        datePanel.setMinimumSize(new java.awt.Dimension(75, 16));
        datePanel.setName(""); // NOI18N
        datePanel.setPreferredSize(new java.awt.Dimension(75, 16));
        datePanel.setLayout(new java.awt.GridLayout(1, 0));

        dateLabel.setFont(new java.awt.Font("Manrope", 0, 13)); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setText("04/01/2026");
        dateLabel.setName(""); // NOI18N
        dateLabel.setRequestFocusEnabled(false);
        datePanel.add(dateLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(datePanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel datePanel;
    private javax.swing.JLabel fileName;
    // End of variables declaration//GEN-END:variables
}
