/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.components;

import java.awt.Color;
import java.time.format.DateTimeFormatter;
import org.kordamp.ikonli.materialdesign2.MaterialDesignC;
import org.kordamp.ikonli.swing.FontIcon;
import org.one.patientmanagement.ui.core.dto.ConsultationData;

/**
 *
 * @author KAROL JOHN
 */
public class ConsultationSummaryRow extends javax.swing.JPanel {

    /**
     * Creates new form MedicalRecordRow
     */
    public ConsultationSummaryRow() {
        initComponents();
        
        icon.setIcon(FontIcon.of(MaterialDesignC.CLIPBOARD_CLOCK_OUTLINE, 12));
        
        jPanel1.putClientProperty("FlatLaf.style", "arc: 30;");
    }
    
    public void setRecordData(ConsultationData consultationData) {
        titleLabel.setText(consultationData.title());
        detailedTypeLabel.setText(consultationData.type().toString());
        
        dateLabel.setText(consultationData.createdAt()
                .toLocalDate()
                .format(DateTimeFormatter.ofPattern("MMM dd, yyyy")));
       doctorLabel.setText(consultationData.doctor());
       
       switch(consultationData.type()) {
            case REFERRAL -> setIcon(Color.decode("#C7E7FF"), Color.decode("#226488"));
            case DIAGNOSIS -> setIcon(Color.decode("#FFDAD6"), Color.decode("#BA1A1A"));
            case GENERAL -> setIcon(Color.decode("#FFDBC7"), Color.decode("#7F5539"));
       }
    }
    
    private void setIcon(Color background, Color foreground) {
        iconPanel.setBackground(background);
        icon.setForeground(foreground);
        
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        detailedTypeLabel = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 5));
        doctorLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        iconPanel = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(250, 234, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 10));

        titleLabel.setFont(new java.awt.Font("Manrope SemiBold", 0, 16)); // NOI18N
        titleLabel.setText("jLabel3");
        jPanel1.add(titleLabel, java.awt.BorderLayout.PAGE_START);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        detailedTypeLabel.setFont(new java.awt.Font("Manrope", 0, 13)); // NOI18N
        detailedTypeLabel.setText("jLabel1");
        jPanel3.add(detailedTypeLabel);
        jPanel3.add(filler1);

        doctorLabel.setFont(new java.awt.Font("Manrope", 0, 13)); // NOI18N
        doctorLabel.setText("jLabel2");
        jPanel3.add(doctorLabel);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 188;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 11, 0);
        add(jPanel1, gridBagConstraints);

        typeLabel.setFont(new java.awt.Font("Manrope Medium", 0, 13)); // NOI18N
        typeLabel.setText("Diagnosis");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(typeLabel, gridBagConstraints);

        dateLabel.setFont(new java.awt.Font("Manrope Medium", 0, 13)); // NOI18N
        dateLabel.setText("Apr 01, 2026 ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(dateLabel, gridBagConstraints);

        iconPanel.setBackground(new java.awt.Color(255, 218, 214));
        iconPanel.setMaximumSize(new java.awt.Dimension(35, 35));
        iconPanel.setMinimumSize(new java.awt.Dimension(35, 35));
        iconPanel.setName(""); // NOI18N
        iconPanel.setPreferredSize(new java.awt.Dimension(35, 35));
        iconPanel.setLayout(new java.awt.GridLayout(1, 0));

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setText("Icon");
        icon.setToolTipText("");
        iconPanel.add(icon);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 12);
        add(iconPanel, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(212, 194, 200));
        jPanel4.setMinimumSize(new java.awt.Dimension(1, 10));
        jPanel4.setPreferredSize(new java.awt.Dimension(1, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 12);
        add(jPanel4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel detailedTypeLabel;
    private javax.swing.JLabel doctorLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel iconPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
