/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.components;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author KAROL JOHN
 */
public class DayOfWeekCard extends ClickablePanel {

    private float alpha = 1;

    /**
     * Creates new form DayOfWeekCard
     */
    public DayOfWeekCard() {
        initComponents();

        timeLabel.putClientProperty("FlatLaf.style", "arc: 999;");
    }

    public void setDayOfWeek(String range, String day) {
        timeLabel.setText(range);
        dayLabel.setText(day);
    }

    @Override
    public void setEnabled(boolean enabled) {
        setVisible(enabled);
        repaint();
    }

    // TODO also override paintComponent for selection logic
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        imagePanel1 = new org.one.patientmanagement.ui.components.ImagePanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        timeLabel = new javax.swing.JLabel();
        dayLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 234, 238));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout(0, 20));

        imagePanel1.setOpaque(false);

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        add(imagePanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 219, 199));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        timeLabel.setFont(new java.awt.Font("Manrope SemiBold", 0, 13)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("7:00 AM - 12:00 PM");
        jPanel1.add(timeLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(jPanel1, gridBagConstraints);

        dayLabel.setFont(new java.awt.Font("Manrope SemiBold", 0, 20)); // NOI18N
        dayLabel.setText("Morning");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel2.add(dayLabel, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dayLabel;
    private org.one.patientmanagement.ui.components.ImagePanel imagePanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables

    public void setSelected(boolean b) {
        if (b) {
            setBackground(Color.decode("#FDD9E7"));
        } else {
            setBackground(Color.decode("#FAEAEE"));
        }
    }
}
