/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.components;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author KAROL JOHN
 */
public class DoctorSelectionRow extends javax.swing.JPanel {

    /**
     * Creates new form DoctorSelectionRow
     */
    public DoctorSelectionRow() {
        initComponents();
    }

    private boolean selected = false;

    public void setSelected(boolean selected) {
        this.selected = selected;
        repaint();
    }

    public boolean isSelected() {
        return selected;
    }

    public void setData(String doctorName, String doctorProfession) {
        this.doctorName.setText(doctorName);
        this.doctorProfession.setText(doctorProfession);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        if (selected) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setColor(new Color(255, 219, 199)); // TODO change highlight color for doctor select
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), 10, 10);
            g2.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        doctorPanel = new javax.swing.JPanel();
        profilePicturePanel2 = new org.one.patientmanagement.ui.components.ProfilePicturePanel();
        jPanel1 = new javax.swing.JPanel();
        doctorName = new javax.swing.JLabel();
        doctorProfession = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(212, 194, 200)));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout(10, 0));

        doctorPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        doctorPanel.setLayout(new java.awt.BorderLayout(10, 0));

        profilePicturePanel2.setPreferredSize(new java.awt.Dimension(60, 120));

        javax.swing.GroupLayout profilePicturePanel2Layout = new javax.swing.GroupLayout(profilePicturePanel2);
        profilePicturePanel2.setLayout(profilePicturePanel2Layout);
        profilePicturePanel2Layout.setHorizontalGroup(
            profilePicturePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        profilePicturePanel2Layout.setVerticalGroup(
            profilePicturePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        doctorPanel.add(profilePicturePanel2, java.awt.BorderLayout.WEST);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        doctorName.setFont(new java.awt.Font("Manrope Medium", 0, 14)); // NOI18N
        doctorName.setText("Dr. Lorem Ipsum");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(doctorName, gridBagConstraints);

        doctorProfession.setFont(new java.awt.Font("Manrope", 0, 12)); // NOI18N
        doctorProfession.setText("Dr. Lorem Ipsum");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        jPanel1.add(doctorProfession, gridBagConstraints);

        doctorPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(doctorPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel doctorName;
    private javax.swing.JPanel doctorPanel;
    private javax.swing.JLabel doctorProfession;
    private javax.swing.JPanel jPanel1;
    private org.one.patientmanagement.ui.components.ProfilePicturePanel profilePicturePanel2;
    // End of variables declaration//GEN-END:variables
}
