/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.components;

import javax.swing.JPanel;
import javax.swing.JProgressBar;

/**
 *
 * @author KAROL JOHN
 */
public final class DoctorStatsCard extends javax.swing.JPanel {

    private final JPanel progressBarContainer = new javax.swing.JPanel();
    private final JProgressBar progressBar = new javax.swing.JProgressBar();

    /**
     * Creates new form TotalStatsCard
     */
    public DoctorStatsCard() {
        initComponents();
    }
    
    public void setContent(String title, String subtitle, String value) {
        titleLabel.setText(title);
        subtitleLabel.setText(subtitle);
        valueLabel.setText(value);
        
        progressBar.setValue(Integer.parseInt(value));
    }

    public void setProgressBar() {
        remove(subtitleLabel);
        
        progressBarContainer.setOpaque(false);
        progressBarContainer.setLayout(new javax.swing.BoxLayout(progressBarContainer, javax.swing.BoxLayout.LINE_AXIS));

        progressBar.setBackground(new java.awt.Color(229, 214, 218));
        progressBar.setForeground(new java.awt.Color(114, 87, 98));
        progressBar.setToolTipText("");
        progressBar.setValue(20);
        progressBar.setMaximumSize(new java.awt.Dimension(32767, 7));
        progressBar.setMinimumSize(new java.awt.Dimension(10, 7));
        progressBar.setPreferredSize(new java.awt.Dimension(146, 7));
        progressBarContainer.add(progressBar);

        add(progressBarContainer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        subtitleLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 234, 238));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        setLayout(new java.awt.GridLayout(3, 0));

        titleLabel.setFont(new java.awt.Font("Manrope Medium", 0, 16)); // NOI18N
        titleLabel.setText("Total Patients");
        add(titleLabel);

        valueLabel.setFont(new java.awt.Font("Manrope SemiBold", 0, 31)); // NOI18N
        valueLabel.setText("67");
        add(valueLabel);

        subtitleLabel.setFont(new java.awt.Font("Manrope", 0, 16)); // NOI18N
        subtitleLabel.setText("Schedule");
        subtitleLabel.setToolTipText("");
        add(subtitleLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
