/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.components;

/**
 *
 * @author KAROL JOHN
 */
public class EditableField extends javax.swing.JPanel {

    /**
     * Creates new form EditableField
     */
    public EditableField() {
        initComponents();
        
        jButton1.addActionListener(l -> {
            jTextField1.setEditable(true);
        });
    }
    
    public void setLabel(String text) {
        jLabel1.setText(text);
    }
    
    public void removeMessage() {
        jLabel2.remove(this);
    }
    
    public String getText() {
        return jTextField1.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout(5, 6));

        jLabel1.setFont(new java.awt.Font("Manrope SemiBold", 0, 16)); // NOI18N
        jLabel1.setText("Username");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Manrope", 0, 16)); // NOI18N
        add(jTextField1, java.awt.BorderLayout.CENTER);

        jLabel2.setText("This is linked to your main contact.");
        add(jLabel2, java.awt.BorderLayout.PAGE_END);

        jButton1.setText("0");
        add(jButton1, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public void setText(String string) {
        jTextField1.setText(string);
    }
}
