/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.components;

import java.awt.Dimension;
import java.awt.FontMetrics;

/**
 *
 * @author KAROL JOHN
 */
public class InfoBox extends javax.swing.JPanel {

    /**
     * Creates new form InfoBox
     */
    public InfoBox() {
        initComponents();

        FontMetrics fm = value.getFontMetrics(value.getFont());
        int h = fm.getHeight() * 2 + 6;

        value.setMaximumSize(new Dimension(200, h));
        value.setMinimumSize(new Dimension(200, h));
        value.setPreferredSize(new Dimension(200, h));
    }

    public void setData(String label, String value) {
        this.label.setText(label);
        this.value.setText("<html>" + value + "</html>");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        value = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        label.setFont(new java.awt.Font("Manrope SemiBold", 0, 14)); // NOI18N
        label.setText("First Name");
        add(label);

        value.setFont(new java.awt.Font("Manrope", 0, 16)); // NOI18N
        value.setText("<html>Karol John</html>");
        value.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(value);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    private javax.swing.JLabel value;
    // End of variables declaration//GEN-END:variables
}
