/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.components;

import java.awt.Dimension;
import java.awt.FontMetrics;

/**
 *
 * @author KAROL JOHN
 */
public class InfoBox extends javax.swing.JPanel {

    /**
     * Creates new form InfoBox
     */
    public InfoBox(String label, String value) {
        initComponents();
        
        this.label.setText(label);
        this.value.setText("<html>" + value + "</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        value = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        label.setFont(new java.awt.Font("Manrope SemiBold", 0, 14)); // NOI18N
        label.setText("First Name");
        add(label, java.awt.BorderLayout.PAGE_START);

        value.setFont(new java.awt.Font("Manrope", 0, 16)); // NOI18N
        value.setText("<html>Karol John</html>");
        value.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(value, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    private javax.swing.JLabel value;
    // End of variables declaration//GEN-END:variables
}
