/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.components;

import java.awt.Color;
import java.time.format.DateTimeFormatter;
import org.one.patientmanagement.domain.dto.ConsultationData;

/**
 *
 * @author KAROL JOHN
 */
public class MedicalRecordRow extends javax.swing.JPanel {

    /**
     * Creates new form MedicalRecordRow
     */
    public MedicalRecordRow() {
        initComponents();
    }
    
    public void setRecordData(ConsultationData consultationData) {
        dateLabel.setText(consultationData.createdAt()
                .toLocalDate()
                .format(DateTimeFormatter.ofPattern("MMM dd, yyyy")));
       descriptionLabel.setText(consultationData.description());
       doctorLabel.setText(consultationData.description());
       
       switch(consultationData.type()) {
            case REFERRAL -> setIcon(Color.decode("#C7E7FF"), Color.decode("#226488"));
            case DIAGNOSIS -> setIcon(Color.decode("##FFDAD6"), Color.decode("#BA1A1A"));
            case GENERAL -> setIcon(Color.decode("#FFDBC7"), Color.decode("#7F5539"));
       }
    }
    
    private void setIcon(Color background, Color foreground) {
        iconPanel.setBackground(background);
        icon.setForeground(foreground);
        
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        doctorLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        iconPanel = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(250, 234, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 10));

        titleLabel.setFont(new java.awt.Font("Manrope SemiBold", 0, 16)); // NOI18N
        titleLabel.setText("jLabel3");
        jPanel1.add(titleLabel, java.awt.BorderLayout.PAGE_START);

        descriptionLabel.setFont(new java.awt.Font("Manrope", 0, 13)); // NOI18N
        descriptionLabel.setText("jLabel4");
        descriptionLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(descriptionLabel, java.awt.BorderLayout.CENTER);

        doctorLabel.setFont(new java.awt.Font("Manrope", 0, 14)); // NOI18N
        doctorLabel.setText("Dr. Ariah Mercado");
        jPanel1.add(doctorLabel, java.awt.BorderLayout.PAGE_END);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 188;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel1, gridBagConstraints);

        typeLabel.setFont(new java.awt.Font("Manrope Medium", 0, 13)); // NOI18N
        typeLabel.setText("Diagnosis");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(typeLabel, gridBagConstraints);

        dateLabel.setFont(new java.awt.Font("Manrope Medium", 0, 13)); // NOI18N
        dateLabel.setText("Apr 01, 2026 ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(dateLabel, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        iconPanel.setBackground(new java.awt.Color(255, 218, 214));
        iconPanel.setMaximumSize(new java.awt.Dimension(35, 35));
        iconPanel.setMinimumSize(new java.awt.Dimension(35, 35));
        iconPanel.setName(""); // NOI18N
        iconPanel.setPreferredSize(new java.awt.Dimension(35, 35));
        iconPanel.setLayout(new java.awt.GridLayout());

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setText("Icon");
        icon.setToolTipText("");
        iconPanel.add(icon);

        jPanel2.add(iconPanel, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel doctorLabel;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel iconPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
