/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.components;

/**
 *
 * @author KAROL JOHN
 */
public class PINField extends javax.swing.JPanel {

    /**
     * Creates new form PINField
     */
    public PINField() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout(0, 10));

        jLabel1.setFont(new java.awt.Font("Manrope SemiBold", 0, 20)); // NOI18N
        jLabel1.setText("Create PIN");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPasswordField1.setBackground(new java.awt.Color(250, 234, 238));
        jPasswordField1.setFont(new java.awt.Font("Manrope", 0, 16)); // NOI18N
        jPasswordField1.setText("123456");
        jPasswordField1.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        jPasswordField1.setMinimumSize(new java.awt.Dimension(64, 30));
        jPasswordField1.setPreferredSize(new java.awt.Dimension(75, 30));
        add(jPasswordField1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
