package org.one.patientmanagement.ui.components;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.time.format.DateTimeFormatter;
import org.one.patientmanagement.ui.core.dto.PrescriptionData;

public final class PrescriptionRow extends javax.swing.JPanel {

    private boolean collapsed = false;
    
    /**
     * Creates new form PrescriptionRow
     */
    public PrescriptionRow() {
        initComponents();
        
        setCursor(new Cursor(Cursor.HAND_CURSOR));

        addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                toggle();
            }
        });
    }

    public void toggle() {
        if (collapsed) expand();
        else collapse();
        
        collapsed = !collapsed;
    }

    public void setPrescriptionData(PrescriptionData prescription) {
        doctorLabel.setText(prescription.doctor());
        frequencyLabel.setText(prescription.frequency());
        durationLabel.setText(prescription.duration().toString());
        medicineLabel.setText(prescription.name());
        dateLabel.setText(
                prescription.createdAt()
                        .toLocalDate()
                        .format(DateTimeFormatter.ofPattern("MM/dd/yyyy"))
        );
        
        if (prescription.isActive()) {
            datePanel.setBackground(Color.decode("#B7F1BA"));
        }
    }

    public void collapse() {
        doctorLabel.setVisible(false);
        frequencyLabel.setVisible(false);
        durationLabel.setVisible(false);

        GridBagLayout layout = (GridBagLayout) getLayout();
        GridBagConstraints gbc = layout.getConstraints(datePanel);
        gbc.gridy = 0; // move to top
        layout.setConstraints(datePanel, gbc);

        revalidate();
        repaint();
    }

    public void expand() {
        doctorLabel.setVisible(true);
        frequencyLabel.setVisible(true);
        durationLabel.setVisible(true);

        GridBagLayout layout = (GridBagLayout) getLayout();
        GridBagConstraints gbc = layout.getConstraints(datePanel);
        gbc.gridy = 2; // restore original position
        layout.setConstraints(datePanel, gbc);

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        medicineLabel = new javax.swing.JLabel();
        frequencyLabel = new javax.swing.JLabel();
        doctorLabel = new javax.swing.JLabel();
        datePanel = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.GridBagLayout());

        medicineLabel.setFont(new java.awt.Font("Manrope Medium", 0, 14)); // NOI18N
        medicineLabel.setText("Amoxicilin 400mg");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(medicineLabel, gridBagConstraints);

        frequencyLabel.setFont(new java.awt.Font("Manrope", 0, 13)); // NOI18N
        frequencyLabel.setText("1x a day");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 0);
        add(frequencyLabel, gridBagConstraints);

        doctorLabel.setFont(new java.awt.Font("Manrope", 0, 13)); // NOI18N
        doctorLabel.setText("Dr. Vince Flores");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 0);
        add(doctorLabel, gridBagConstraints);

        datePanel.setBackground(new java.awt.Color(255, 240, 244));
        datePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        datePanel.setMaximumSize(new java.awt.Dimension(32767, 16));
        datePanel.setMinimumSize(new java.awt.Dimension(75, 16));
        datePanel.setName(""); // NOI18N
        datePanel.setPreferredSize(new java.awt.Dimension(75, 16));
        datePanel.setLayout(new java.awt.GridLayout());

        dateLabel.setFont(new java.awt.Font("Manrope", 0, 13)); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setText("04/01/2026");
        dateLabel.setName(""); // NOI18N
        dateLabel.setRequestFocusEnabled(false);
        datePanel.add(dateLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(datePanel, gridBagConstraints);

        durationLabel.setFont(new java.awt.Font("Manrope", 0, 13)); // NOI18N
        durationLabel.setText("1 week");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(durationLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel datePanel;
    private javax.swing.JLabel doctorLabel;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JLabel frequencyLabel;
    private javax.swing.JLabel medicineLabel;
    // End of variables declaration//GEN-END:variables
}
