/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.components;

import java.util.List;
import javax.swing.Box;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.one.patientmanagement.domain.dto.QueueData;
import org.one.patientmanagement.domain.enums.AppointmentStatus;
import org.one.patientmanagement.ui.controller.ControllerBound;
import org.one.patientmanagement.ui.controller.doctor.QueueController;

/**
 *
 * @author KAROL JOHN
 */
public class QueueListContainer extends javax.swing.JPanel implements ControllerBound<QueueController.QueueListController> {

    private QueueController.QueueListController controller;

    /**
     * Creates new form QueueListContainer
     */
    public QueueListContainer() {
        initComponents();

        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.getViewport().setBackground(null);
        jScrollPane1.setBackground(null);
        
        searchField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                controller.onSearch(searchField.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                controller.onSearch(searchField.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                controller.onSearch(searchField.getText());
            }
        });
    }
    
    public void setInfo(AppointmentStatus status, int size) {
        statusBadgePanel1.setStatus(status);
        countLabel.setText(String.valueOf(size));
    }

    public void loadQueue(AppointmentStatus status, List<QueueData> queues) {
        clearQueue();
        queues.forEach(q -> {
            var row = new DetailedPatientRow();
            addQueueRow(row);
        });
    }
    
    public void replaceQueueBox(JPanel panel) {
        remove(queueBox);
        add(panel, java.awt.BorderLayout.CENTER);
    }

    private void addQueueRow(DetailedPatientRow row) {
        queueListPanel.add(row);
        queueListPanel.add(Box.createVerticalStrut(5));
        queueListPanel.revalidate();
        queueListPanel.repaint();
    }

    public void clearQueue() {
        queueListPanel.removeAll();
        queueListPanel.revalidate();
        queueListPanel.repaint();
    }
    
    public StatusBadgePanel getStatusBadgePanel() {
        return statusBadgePanel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        statusBadgePanel1 = new org.one.patientmanagement.ui.components.StatusBadgePanel();
        countLabel = new javax.swing.JLabel();
        queueBox = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        queueListPanel = new org.one.patientmanagement.ui.components.FillWidthPanel();

        setBackground(new java.awt.Color(250, 234, 238));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout(0, 12));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout(6, 0));
        jPanel3.add(statusBadgePanel1, java.awt.BorderLayout.WEST);

        countLabel.setText("jLabel1");
        jPanel3.add(countLabel, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.PAGE_START);

        queueBox.setBackground(new java.awt.Color(250, 234, 238));
        queueBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        queueBox.setLayout(new java.awt.BorderLayout(0, 6));

        searchField.setFont(new java.awt.Font("Manrope", 0, 13)); // NOI18N
        searchField.setText("jTextField1");
        searchField.setPreferredSize(new java.awt.Dimension(80, 35));
        queueBox.add(searchField, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBorder(null);

        queueListPanel.setLayout(new javax.swing.BoxLayout(queueListPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(queueListPanel);

        queueBox.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(queueBox, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel countLabel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel queueBox;
    private org.one.patientmanagement.ui.components.FillWidthPanel queueListPanel;
    private javax.swing.JTextField searchField;
    private org.one.patientmanagement.ui.components.StatusBadgePanel statusBadgePanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setController(QueueController.QueueListController controller) {
        this.controller = controller;
    }
}
