/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.components;

import javax.swing.BorderFactory;

/**
 *
 * @author KAROL JOHN
 */
public class QueueListContainer extends javax.swing.JPanel {

    /**
     * Creates new form QueueListContainer
     */
    public QueueListContainer() {
        initComponents();
        
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.getViewport().setBackground(null);
        jScrollPane1.setBackground(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        statusBadgePanel1 = new org.one.patientmanagement.ui.components.StatusBadgePanel();
        countLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(250, 234, 238));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout(0, 12));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout(6, 0));
        jPanel3.add(statusBadgePanel1, java.awt.BorderLayout.WEST);

        countLabel.setText("jLabel1");
        jPanel3.add(countLabel, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(250, 234, 238));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        jPanel2.setLayout(new java.awt.BorderLayout(0, 6));

        jTextField1.setFont(new java.awt.Font("Manrope", 0, 13)); // NOI18N
        jTextField1.setText("jTextField1");
        jTextField1.setPreferredSize(new java.awt.Dimension(80, 35));
        jPanel2.add(jTextField1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBorder(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(jPanel1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel countLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private org.one.patientmanagement.ui.components.StatusBadgePanel statusBadgePanel1;
    // End of variables declaration//GEN-END:variables
}
