/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.components;

/**
 *
 * @author KAROL JOHN
 */
public class TakePhoto extends javax.swing.JPanel {

    /**
     * Creates new form TakePhoto
     */
    public TakePhoto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        profilePicturePanel2 = new org.one.patientmanagement.ui.components.ProfilePicturePanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(20, 0));

        jPanel1.setLayout(new java.awt.BorderLayout(10, 0));

        javax.swing.GroupLayout profilePicturePanel2Layout = new javax.swing.GroupLayout(profilePicturePanel2);
        profilePicturePanel2.setLayout(profilePicturePanel2Layout);
        profilePicturePanel2Layout.setHorizontalGroup(
            profilePicturePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        profilePicturePanel2Layout.setVerticalGroup(
            profilePicturePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(profilePicturePanel2, java.awt.BorderLayout.WEST);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setBackground(new java.awt.Color(255, 216, 231));
        jButton1.setFont(new java.awt.Font("Manrope SemiBold", 0, 16)); // NOI18N
        jButton1.setText("Take a photo");
        jButton1.setMaximumSize(new java.awt.Dimension(140, 50));
        jPanel2.add(jButton1);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.one.patientmanagement.ui.components.ProfilePicturePanel profilePicturePanel2;
    // End of variables declaration//GEN-END:variables
}
