/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.components;

/**
 *
 * @author KAROL JOHN
 */
public class TextField extends javax.swing.JPanel {

    /**
     * Creates new form TextField
     */
    public TextField() {
        initComponents();
    }
    
    public void setLabel(String name) {
        jLabel1.setText(name);
    }
    
    public String getFieldText() {
        return jTextField1.getText();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout(5, 5));

        jLabel1.setFont(new java.awt.Font("Manrope SemiBold", 0, 14)); // NOI18N
        jLabel1.setText("Birthday");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jTextField1.setBackground(new java.awt.Color(250, 234, 238));
        jTextField1.setFont(new java.awt.Font("Manrope", 0, 16)); // NOI18N
        jTextField1.setText("jTextField1");
        jTextField1.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        jTextField1.setMinimumSize(new java.awt.Dimension(64, 30));
        jTextField1.setPreferredSize(new java.awt.Dimension(92, 30));
        add(jTextField1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
