/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.components;

import java.awt.event.ActionListener;
import org.one.patientmanagement.domain.enums.VitalsType;
import org.one.patientmanagement.domain.models.Vitals;

/**
 *
 * @author KAROL JOHN
 */
public class VitalsCard extends javax.swing.JPanel {

    /**
     * Creates new form VitalsCard
     */
    public VitalsCard() {
        initComponents();
    }
    
    public void setVitals(VitalsType type, Vitals vitals) {
        switch (type) {
            case WEIGHT -> apply("Weight", String.valueOf(vitals.weight()), "kg");
            case TEMPERATURE -> apply("Temperature", String.valueOf(vitals.temperature()), "C");
            case HEART_RATE -> apply("Heart Rate", String.valueOf(vitals.heartRate()), "bpm");
            case BLOOD_PRESSURE -> apply("Blood Pressure", String.valueOf(vitals.systolicBp()) + '/' + String.valueOf(vitals.diastolicBp()), null);
        }
    }
    
    public void apply(String title, String value, String unit) {
        titleLabel.setText("<html>" + title + "</html>");
        valueLabel.setText(value);
        
        if (unit == null) {
            unitLabel.setVisible(false);
        } else unitLabel.setText(unit);
        
        repaint();
        revalidate();
    }
    
    public void setEditListener(ActionListener l) {
        editBtn.addActionListener(l);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titleLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        unitLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(250, 234, 238));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));
        setLayout(new java.awt.GridBagLayout());

        titleLabel.setFont(new java.awt.Font("Manrope Medium", 0, 16)); // NOI18N
        titleLabel.setText("<html>Heart Rate</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(titleLabel, gridBagConstraints);

        valueLabel.setFont(new java.awt.Font("Manrope SemiBold", 0, 25)); // NOI18N
        valueLabel.setText("72");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(valueLabel, gridBagConstraints);

        icon.setFont(new java.awt.Font("Dialog", 0, 25)); // NOI18N
        icon.setText("o");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(icon, gridBagConstraints);

        editBtn.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(editBtn, gridBagConstraints);

        unitLabel.setFont(new java.awt.Font("Manrope Medium", 0, 16)); // NOI18N
        unitLabel.setText("bpm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 0);
        add(unitLabel, gridBagConstraints);

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel unitLabel;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
