/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.view;

/**
 *
 * @author Lei
 */
public class DoctorLogin extends javax.swing.JPanel {

    public interface LoginSubmitListener {

        void onSubmit(String password);
    }

    private LoginSubmitListener submitListener;

    public DoctorLogin() {
        initComponents();

        submitButton.putClientProperty("FlatLaf.style", "arc: 999;");
        submitButton.addActionListener(e -> {
            submitListener.onSubmit(
                    new String(jPasswordField1.getPassword())
            );
        });

        stepProgress1.removeBack();
        
        backdrop2.setImage("/images/doctor_backdrop.png");
        backdrop2.setBadge("Doctor Panel");
        backdrop2.setHeading("Welcome back, Doctor");
    }
    
    public void setSubmitListener(LoginSubmitListener submitListener) {
        this.submitListener = submitListener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenuItem1 = new javax.swing.JMenuItem();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        stepProgress1 = new org.one.patientmanagement.ui.components.StepProgress();
        jPanel2 = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        formContainer = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Existing_Email1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        submitButton = new javax.swing.JButton();
        backdrop2 = new org.one.patientmanagement.ui.components.Backdrop();

        jMenuItem1.setText("jMenuItem1");

        setBackground(new java.awt.Color(255, 248, 248));
        setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane1.setDividerSize(0);
        jSplitPane1.setEnabled(false);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(stepProgress1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        formPanel.setBackground(new java.awt.Color(250, 234, 238));
        formPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 70, 70, 70));
        formPanel.setPreferredSize(new java.awt.Dimension(500, 400));
        formPanel.setLayout(new java.awt.BorderLayout(0, 20));

        formContainer.setOpaque(false);
        formContainer.setPreferredSize(new java.awt.Dimension(1166, 300));
        formContainer.setLayout(new java.awt.GridBagLayout());

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(533, 68));
        jPanel4.setLayout(new java.awt.BorderLayout(0, 10));

        Existing_Email1.setFont(new java.awt.Font("Manrope SemiBold", 0, 20)); // NOI18N
        Existing_Email1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Existing_Email1.setText("Login with PIN");
        Existing_Email1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel4.add(Existing_Email1, java.awt.BorderLayout.PAGE_START);

        jPasswordField1.setBackground(new java.awt.Color(255, 240, 244));
        jPasswordField1.setFont(new java.awt.Font("Manrope", 0, 16)); // NOI18N
        jPasswordField1.setText("123456");
        jPanel4.add(jPasswordField1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.weightx = 1.0;
        formContainer.add(jPanel4, gridBagConstraints);

        formPanel.add(formContainer, java.awt.BorderLayout.CENTER);

        submitButton.setBackground(new java.awt.Color(137, 74, 105));
        submitButton.setFont(new java.awt.Font("Manrope SemiBold", 0, 16)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Proceed");
        submitButton.setPreferredSize(new java.awt.Dimension(95, 55));
        formPanel.add(submitButton, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(formPanel, gridBagConstraints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel1);
        jSplitPane1.setLeftComponent(backdrop2);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Existing_Email1;
    private org.one.patientmanagement.ui.components.Backdrop backdrop2;
    private javax.swing.JPanel formContainer;
    private javax.swing.JPanel formPanel;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSplitPane jSplitPane1;
    private org.one.patientmanagement.ui.components.StepProgress stepProgress1;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
