/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.view;

import java.util.List;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.one.patientmanagement.ui.core.dto.QueueData;
import org.one.patientmanagement.domain.enums.AppointmentBlock;
import org.one.patientmanagement.domain.enums.AppointmentStatus;
import org.one.patientmanagement.domain.models.Schedule;
import org.one.patientmanagement.ui.components.ClickablePanel;
import org.one.patientmanagement.ui.components.DetailedPatientRow;
import org.one.patientmanagement.ui.components.PatientRow;
import org.one.patientmanagement.ui.components.QueueListContainer;
import org.one.patientmanagement.ui.components.TodaySchedule;
import org.one.patientmanagement.ui.controller.ControllerBound;
import org.one.patientmanagement.ui.controller.doctor.QueueController;

/**
 *
 * @author KAROL JOHN
 */
public class DoctorPatientQueue extends javax.swing.JPanel implements ControllerBound<QueueController> {

    private QueueController controller;
    private ClickablePanel.ClickListenerObj<QueueData> clickListener;

    /**
     * Creates new form PatientQueue
     */
    public DoctorPatientQueue() {
        initComponents();
    }
    
    public void loadSchedules(List<Schedule> schedules) {
        todaySchedule.generateCalendar(schedules);
    }
    
    public void setDaySelectListener(TodaySchedule.DaySelectListener listener) {
        todaySchedule.setDaySelectListener(listener);
    }

    public void loadQueue(AppointmentBlock block, Schedule schedule, QueueData withDoctor, List<QueueData> queues) {
        JPanel panel = block == AppointmentBlock.MORNING ? morningPanel : afternoonPanel;

        var available = schedule.blocks().contains(block);
        panel.setEnabled(available);
        if (!available) {
            return;
        }

        JPanel panelList = block == AppointmentBlock.MORNING ? morningList : afternoonList;
        JLabel panelTime = block == AppointmentBlock.MORNING ? morningTime : afternoonTime;

        panelTime.setText(schedule.timeRange(block));
        clearQueue(panelList);

        for (var status : AppointmentStatus.values()) {
            if (withDoctor != null && status == AppointmentStatus.WITH_DOCTOR) {
                var row = new QueueListContainer();
                var queueRow = new DetailedPatientRow();
                
                queueRow.setClickListener(l -> { clickListener.onClick(withDoctor); });
                
                row.replaceQueueBox(queueRow);
                row.getStatusBadgePanel().setStatus(AppointmentStatus.WITH_DOCTOR);
                
                addQueueRow(row, panelList);
            }

            var row = new QueueListContainer();

            row.getStatusBadgePanel().setStatus(status);
            
            final QueueController.QueueListController attachQueueListController = controller.attachQueueListController(row);
            attachQueueListController.loadQueueList(status, queues);
            attachQueueListController.loadQueueInfo();
            
            addQueueRow(row, panelList);
        }
    }
    
    public void setRowClickListener(ClickablePanel.ClickListenerObj<QueueData> clickListener) {
        this.clickListener = clickListener;
    }

    private void addQueueRow(QueueListContainer row, JPanel panelList) {
        panelList.add(row);
        panelList.add(Box.createVerticalStrut(5));
        panelList.revalidate();
        panelList.repaint();
    }

    public void clearQueue(JPanel panelList) {
        panelList.removeAll();
        panelList.revalidate();
        panelList.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        todaySchedule = new org.one.patientmanagement.ui.components.TodaySchedule();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        jPanel3 = new javax.swing.JPanel();
        morningPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        morningTime = new javax.swing.JLabel();
        morningList = new javax.swing.JPanel();
        divider = new javax.swing.JPanel();
        afternoonPanel = new javax.swing.JPanel();
        afternoonList = new javax.swing.JPanel();
        headerPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        afternoonTime = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(999999999, 47));
        jPanel1.setPreferredSize(new java.awt.Dimension(892, 47));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 31)); // NOI18N
        jLabel1.setText("Patient Queue");
        jPanel1.add(jLabel1);

        jPanel2.add(jPanel1);
        jPanel2.add(filler1);

        todaySchedule.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        todaySchedule.setMinimumSize(new java.awt.Dimension(0, 200));
        todaySchedule.setPreferredSize(new java.awt.Dimension(850, 200));
        jPanel2.add(todaySchedule);
        jPanel2.add(filler2);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        morningPanel.setLayout(new java.awt.BorderLayout(0, 25));

        headerPanel.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel2.setText("Morning");
        headerPanel.add(jLabel2, java.awt.BorderLayout.WEST);

        morningTime.setFont(new java.awt.Font("Manrope SemiBold", 0, 16)); // NOI18N
        morningTime.setText("jLabel2");
        headerPanel.add(morningTime, java.awt.BorderLayout.EAST);

        morningPanel.add(headerPanel, java.awt.BorderLayout.PAGE_START);

        morningList.setLayout(new java.awt.GridLayout(3, 0, 0, 20));
        morningPanel.add(morningList, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(morningPanel, gridBagConstraints);

        divider.setBackground(new java.awt.Color(212, 194, 200));
        divider.setPreferredSize(new java.awt.Dimension(1, 100));

        javax.swing.GroupLayout dividerLayout = new javax.swing.GroupLayout(divider);
        divider.setLayout(dividerLayout);
        dividerLayout.setHorizontalGroup(
            dividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        dividerLayout.setVerticalGroup(
            dividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 26, 0, 26);
        jPanel3.add(divider, gridBagConstraints);

        afternoonPanel.setLayout(new java.awt.BorderLayout(0, 25));

        afternoonList.setLayout(new java.awt.GridLayout(3, 0, 0, 20));
        afternoonPanel.add(afternoonList, java.awt.BorderLayout.CENTER);

        headerPanel2.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel6.setText("Afternoon");
        headerPanel2.add(jLabel6, java.awt.BorderLayout.WEST);

        afternoonTime.setFont(new java.awt.Font("Manrope SemiBold", 0, 16)); // NOI18N
        afternoonTime.setText("jLabel2");
        headerPanel2.add(afternoonTime, java.awt.BorderLayout.EAST);

        afternoonPanel.add(headerPanel2, java.awt.BorderLayout.PAGE_START);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(afternoonPanel, gridBagConstraints);

        jPanel2.add(jPanel3);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel afternoonList;
    private javax.swing.JPanel afternoonPanel;
    private javax.swing.JLabel afternoonTime;
    private javax.swing.JPanel divider;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel headerPanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel morningList;
    private javax.swing.JPanel morningPanel;
    private javax.swing.JLabel morningTime;
    private org.one.patientmanagement.ui.components.TodaySchedule todaySchedule;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setController(QueueController controller) {
        this.controller = controller;
    }
}
