/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.view;

import java.awt.CardLayout;
import javax.swing.JPanel;
import org.one.patientmanagement.ui.components.NavigationSidebar;
import org.one.patientmanagement.ui.model.DoctorViewModel;

/**
 *
 * @author KAROL JOHN
 */
public class DoctorView extends javax.swing.JPanel {

    /**
     * Creates new form DoctorView
     */
    
    public DoctorView(DoctorViewModel model) {
        initComponents();
        
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.getViewport().setBackground(null);
        jScrollPane1.setBackground(null);
        
        topBar1.setGreeting(model.getDoctor().name());
    }
    
    public NavigationSidebar getNavigationSidebar() {
        return navigationSidebar1;
    }
    
    public JPanel getNavigationContainer() {
        return container;
    }
    
    public CardLayout getNavigationLayout() {
        return (CardLayout) container.getLayout();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigationSidebar1 = new org.one.patientmanagement.ui.components.NavigationSidebar();
        jPanel2 = new javax.swing.JPanel();
        topBar1 = new org.one.patientmanagement.ui.components.TopBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        container = new org.one.patientmanagement.ui.components.FillWidthPanel();

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(topBar1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setOpaque(false);

        container.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        container.setLayout(new java.awt.CardLayout());
        jScrollPane1.setViewportView(container);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navigationSidebar1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navigationSidebar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.one.patientmanagement.ui.components.FillWidthPanel container;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.one.patientmanagement.ui.components.NavigationSidebar navigationSidebar1;
    private org.one.patientmanagement.ui.components.TopBar topBar1;
    // End of variables declaration//GEN-END:variables
}
