/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.view;

import org.one.patientmanagement.ui.controller.doctor.PatientDashboardController;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.Box;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.one.patientmanagement.domain.dto.ConsultationData;
import org.one.patientmanagement.domain.dto.PrescriptionData;
import org.one.patientmanagement.domain.enums.VitalsType;
import org.one.patientmanagement.domain.models.Patient;
import org.one.patientmanagement.domain.models.Vitals;
import org.one.patientmanagement.ui.components.InfoBox;
import org.one.patientmanagement.ui.components.MedicalRecordRow;
import org.one.patientmanagement.ui.components.PrescriptionRow;
import org.one.patientmanagement.ui.components.VitalsCard;
import org.one.patientmanagement.ui.controller.ControllerBound;

/**
 *
 * @author KAROL JOHN
 */
public class DoctorPatientDashboard extends javax.swing.JPanel implements ControllerBound<PatientDashboardController> {

    private PatientDashboardController controller;

    /**
     * Creates new form DoctorPatientDashboard
     */
    public DoctorPatientDashboard() {
        initComponents();

        searchField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                controller.onSearch(searchField.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                controller.onSearch(searchField.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                controller.onSearch(searchField.getText());
            }
        });
    }

    public void setInfo(Patient patient, Vitals vitals) {
        basicInformationList.add(new InfoBox("First Name", patient.firstName()));
        basicInformationList.add(new InfoBox("Last Name", patient.lastName()));
        basicInformationList.add(new InfoBox("Address", patient.address()));
        basicInformationList.add(new InfoBox("Birthday", patient.birthday().format(DateTimeFormatter.ofPattern("MM/dd/yyyy"))));
        basicInformationList.add(new InfoBox("Age", String.valueOf(patient.getAge()) + " y/o"));
        basicInformationList.add(new InfoBox("Sex", patient.sex()));
        basicInformationList.add(new InfoBox("Blood type", patient.bloodType()));
        fullNameLabel.setText(patient.firstName() + " " + patient.lastName());
        
        setVitalsCard(vitalsCard1, VitalsType.HEART_RATE, vitals);
        setVitalsCard(vitalsCard2, VitalsType.BLOOD_PRESSURE, vitals);
        setVitalsCard(vitalsCard3, VitalsType.TEMPERATURE, vitals);
        setVitalsCard(vitalsCard4, VitalsType.WEIGHT, vitals);
        
    }

    public void setVitalsCard(VitalsCard vitalsCard, VitalsType type, Vitals vitals) {
        vitalsCard.setVitals(type, vitals);
        vitalsCard.setEditListener(e
                -> controller.onVitalsEdit(type, v -> vitalsCard1.setVitals(type, v))
        );
    }

    public void loadPrescription(List<PrescriptionData> prescriptions) {
        clearRows(prescriptionList);
        prescriptions.stream().forEach(p -> {
            var row = new PrescriptionRow();

            row.setPrescriptionData(p);
            addRow(row, prescriptionList);
        });
    }

    private void addRow(JPanel row, JPanel panelList) {
        panelList.add(row);
        panelList.add(Box.createVerticalStrut(5));
        panelList.revalidate();
        panelList.repaint();
    }

    public void clearRows(JPanel panelList) {
        panelList.removeAll();
        panelList.revalidate();
        panelList.repaint();
    }

    public void loadConsultation(List<ConsultationData> consultations) {
        clearRows(consultationList);
        consultations.stream().forEach(c -> {
            var row = new MedicalRecordRow();

            row.setRecordData(c);
            addRow(row, consultationList);
        });
    }

    // TODO contemplate on attachments
    public void loadAttachments() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        fillWidthPanel1 = new org.one.patientmanagement.ui.components.FillWidthPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        vitalsCard1 = new org.one.patientmanagement.ui.components.VitalsCard();
        vitalsCard2 = new org.one.patientmanagement.ui.components.VitalsCard();
        vitalsCard3 = new org.one.patientmanagement.ui.components.VitalsCard();
        vitalsCard4 = new org.one.patientmanagement.ui.components.VitalsCard();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25));
        prescriptionPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prescriptionList = new org.one.patientmanagement.ui.components.FillWidthPanel();
        prescriptionAddBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        medicalRecordAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        consultationList = new org.one.patientmanagement.ui.components.FillWidthPanel();
        searchField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        fullNameLabel = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 0));
        jPanel17 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        basicInformationList = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 0));
        jPanel15 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        contactsList = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(270);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setEnabled(false);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setToolTipText("");

        fillWidthPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel8.setMaximumSize(new java.awt.Dimension(295, 2147483647));
        jPanel8.setMinimumSize(new java.awt.Dimension(295, 320));
        jPanel8.setName(""); // NOI18N
        jPanel8.setPreferredSize(new java.awt.Dimension(295, 662));
        jPanel8.setRequestFocusEnabled(false);
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setMaximumSize(new java.awt.Dimension(290, 290));
        jPanel5.setMinimumSize(new java.awt.Dimension(290, 290));
        jPanel5.setPreferredSize(new java.awt.Dimension(290, 290));
        jPanel5.setRequestFocusEnabled(false);
        jPanel5.setLayout(new java.awt.GridLayout(2, 2, 6, 6));
        jPanel5.add(vitalsCard1);
        jPanel5.add(vitalsCard2);
        jPanel5.add(vitalsCard3);
        jPanel5.add(vitalsCard4);

        jPanel8.add(jPanel5);
        jPanel8.add(filler3);

        prescriptionPanel.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setBorder(null);

        prescriptionList.setBackground(new java.awt.Color(204, 204, 204));
        prescriptionList.setLayout(new javax.swing.BoxLayout(prescriptionList, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(prescriptionList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        prescriptionPanel.add(jScrollPane1, gridBagConstraints);

        prescriptionAddBtn.setBackground(new java.awt.Color(255, 216, 231));
        prescriptionAddBtn.setFont(new java.awt.Font("Manrope Medium", 0, 14)); // NOI18N
        prescriptionAddBtn.setText("Add");
        prescriptionAddBtn.addActionListener(this::prescriptionAddBtnActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        prescriptionPanel.add(prescriptionAddBtn, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel2.setText("Prescription");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        prescriptionPanel.add(jLabel2, gridBagConstraints);

        jPanel8.add(prescriptionPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(22, 22, 22, 22);
        fillWidthPanel1.add(jPanel8, gridBagConstraints);

        jPanel10.setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 25)); // NOI18N
        jLabel1.setText("<html>Medical Record History Timeline</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(jLabel1, gridBagConstraints);

        medicalRecordAdd.setBackground(new java.awt.Color(255, 216, 231));
        medicalRecordAdd.setFont(new java.awt.Font("Manrope Medium", 0, 14)); // NOI18N
        medicalRecordAdd.setText("Add");
        medicalRecordAdd.addActionListener(this::medicalRecordAddActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel3.add(medicalRecordAdd, gridBagConstraints);

        jScrollPane2.setBorder(null);

        consultationList.setLayout(new javax.swing.BoxLayout(consultationList, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(consultationList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jScrollPane2, gridBagConstraints);

        searchField.setFont(new java.awt.Font("Manrope", 0, 16)); // NOI18N
        searchField.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 600;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(21, 0, 21, 0);
        jPanel3.add(searchField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel10.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(22, 22, 22, 22);
        fillWidthPanel1.add(jPanel10, gridBagConstraints);

        jScrollPane3.setViewportView(fillWidthPanel1);

        jPanel2.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 891, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setRightComponent(jPanel2);

        jPanel11.setBackground(new java.awt.Color(255, 240, 244));
        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));

        jPanel12.setBackground(new java.awt.Color(255, 216, 231));
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        fullNameLabel.setFont(new java.awt.Font("Manrope SemiBold", 0, 14)); // NOI18N
        fullNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullNameLabel.setText("Karol John Dela Cruz");
        jPanel12.add(fullNameLabel);

        jPanel11.add(jPanel12);
        jPanel11.add(filler1);

        jPanel17.setOpaque(false);
        jPanel17.setLayout(new java.awt.BorderLayout(20, 20));

        jLabel6.setFont(new java.awt.Font("Manrope SemiBold", 0, 16)); // NOI18N
        jLabel6.setText("Basic Information");
        jPanel17.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        basicInformationList.setOpaque(false);
        jPanel17.add(basicInformationList, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel17);
        jPanel11.add(filler2);

        jPanel15.setOpaque(false);
        jPanel15.setLayout(new java.awt.BorderLayout(20, 20));

        jLabel5.setFont(new java.awt.Font("Manrope SemiBold", 0, 16)); // NOI18N
        jLabel5.setText("Contacts");
        jPanel15.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        contactsList.setOpaque(false);
        jPanel15.add(contactsList, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel15);

        jSplitPane1.setLeftComponent(jPanel11);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void prescriptionAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescriptionAddBtnActionPerformed
        controller.onPrescriptionAdd();
    }//GEN-LAST:event_prescriptionAddBtnActionPerformed

    private void medicalRecordAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalRecordAddActionPerformed
        controller.onMedicalRecordAdd();
    }//GEN-LAST:event_medicalRecordAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basicInformationList;
    private org.one.patientmanagement.ui.components.FillWidthPanel consultationList;
    private javax.swing.JPanel contactsList;
    private org.one.patientmanagement.ui.components.FillWidthPanel fillWidthPanel1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton medicalRecordAdd;
    private javax.swing.JButton prescriptionAddBtn;
    private org.one.patientmanagement.ui.components.FillWidthPanel prescriptionList;
    private javax.swing.JPanel prescriptionPanel;
    private javax.swing.JTextField searchField;
    private org.one.patientmanagement.ui.components.VitalsCard vitalsCard1;
    private org.one.patientmanagement.ui.components.VitalsCard vitalsCard2;
    private org.one.patientmanagement.ui.components.VitalsCard vitalsCard3;
    private org.one.patientmanagement.ui.components.VitalsCard vitalsCard4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setController(PatientDashboardController controller) {
        this.controller = controller;
    }
}
