/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.view;

import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.Box;
import org.one.patientmanagement.domain.models.Patient;
import org.one.patientmanagement.ui.components.ClickablePanel.ClickListenerObj;
import org.one.patientmanagement.ui.components.PatientRecordRow;
import org.one.patientmanagement.ui.controller.ControllerBound;
import org.one.patientmanagement.ui.controller.doctor.PatientRecordsController;

/**
 *
 * @author KAROL JOHN
 */
public class DoctorPatientRecords extends javax.swing.JPanel implements ControllerBound<PatientRecordsController> {

    private PatientRecordsController controller;
    private ClickListenerObj<Patient> clickListener;

    /**
     * Creates new form PatientRecords
     */
    public DoctorPatientRecords() {
        initComponents();
    }

    @Override
    public void setController(PatientRecordsController controller) {
        this.controller = controller;
    }
    
    public void loadPatients(List<Patient> patients) {
        clearRows();
        patients.stream().forEach(p -> {
            var row = new PatientRecordRow();
            row.setClickListener(l -> { clickListener.onClick(p); });
            
            row.setPatientData(p.getFullName(), p.getSchemedId(), p.sex(), p.birthday().format(DateTimeFormatter.ofPattern("MM/dd/yyyy")));
            addRow(row);
        });
    }
    
    public void setRowClickListener(ClickListenerObj<Patient> clickListener) {
        this.clickListener = clickListener;
    }
    
    private void addRow(PatientRecordRow row) {
        patientList.add(row);
        patientList.add(Box.createVerticalStrut(5));
        patientList.revalidate();
        patientList.repaint();
    }

    public void clearRows() {
        patientList.removeAll();
        patientList.revalidate();
        patientList.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientList = new org.one.patientmanagement.ui.components.FillWidthPanel();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 31)); // NOI18N
        jLabel1.setText("Patient Records");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel1, gridBagConstraints);

        searchField.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 414;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(14, 0, 14, 0);
        add(searchField, gridBagConstraints);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);

        patientList.setOpaque(false);
        patientList.setLayout(new javax.swing.BoxLayout(patientList, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(patientList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1000;
        gridBagConstraints.ipady = 437;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.one.patientmanagement.ui.components.FillWidthPanel patientList;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
