/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.view;

/**
 *
 * @author KAROL JOHN
 */
public class PatientDashboard extends javax.swing.JPanel {

    /**
     * Creates new form PatientDashboard
     */
    public PatientDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel12 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        stepProgress1 = new org.one.patientmanagement.ui.components.StepProgress();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fillWidthPanel1 = new org.one.patientmanagement.ui.components.FillWidthPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        infoBoxPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        editableField1 = new org.one.patientmanagement.ui.components.EditableField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        editableField2 = new org.one.patientmanagement.ui.components.EditableField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30));
        jPanel8 = new javax.swing.JPanel();
        pINField2 = new org.one.patientmanagement.ui.components.PINField();
        pINField1 = new org.one.patientmanagement.ui.components.PINField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        jPanel11 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel12.setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(stepProgress1, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new java.awt.BorderLayout(0, 20));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 31)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Your appointment");
        jPanel3.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(null);
        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        fillWidthPanel1.setLayout(new javax.swing.BoxLayout(fillWidthPanel1, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(fillWidthPanel1);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel5.add(jPanel3, gridBagConstraints);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel12.add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 40, 40));
        jPanel2.setLayout(new java.awt.GridLayout(2, 0, 10, 16));

        jPanel7.setBackground(new java.awt.Color(255, 240, 244));
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        jPanel7.setLayout(new java.awt.BorderLayout(0, 20));

        jLabel3.setText("jLabel3");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(26, 1, 1, 1));
        jPanel7.add(jLabel3, java.awt.BorderLayout.PAGE_END);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridBagLayout());

        infoBoxPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 528;
        gridBagConstraints.ipady = 267;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel6.add(infoBoxPanel, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Manrope Medium", 0, 14)); // NOI18N
        jButton1.setText("Take a photo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel6.add(jButton1, gridBagConstraints);

        jLabel4.setText("pic");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel6.add(jLabel4, gridBagConstraints);

        jPanel7.add(jPanel6, java.awt.BorderLayout.CENTER);

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel5.setText("Your profile");
        jPanel7.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel7);

        jPanel9.setBackground(new java.awt.Color(255, 240, 244));
        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        jPanel9.setLayout(new java.awt.BorderLayout(0, 20));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel2.setText("Account Credentials");
        jPanel9.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));

        editableField1.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        editableField1.setMinimumSize(new java.awt.Dimension(91, 100));
        editableField1.setPreferredSize(new java.awt.Dimension(119, 100));
        jPanel10.add(editableField1);
        jPanel10.add(filler1);

        editableField2.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        editableField2.setMinimumSize(new java.awt.Dimension(91, 100));
        editableField2.setName(""); // NOI18N
        editableField2.setPreferredSize(new java.awt.Dimension(119, 100));
        jPanel10.add(editableField2);
        jPanel10.add(filler2);

        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 90));
        jPanel8.setMinimumSize(new java.awt.Dimension(304, 90));
        jPanel8.setName(""); // NOI18N
        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(353, 90));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0, 80, 10));
        jPanel8.add(pINField2);
        jPanel8.add(pINField1);

        jPanel10.add(jPanel8);
        jPanel10.add(filler3);

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        jButton2.setFont(new java.awt.Font("Manrope SemiBold", 0, 14)); // NOI18N
        jButton2.setText("Save New PIN");
        jPanel11.add(jButton2);

        jPanel10.add(jPanel11);

        jPanel9.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel9);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = -110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        jPanel12.add(jPanel2, gridBagConstraints);

        add(jPanel12, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.one.patientmanagement.ui.components.EditableField editableField1;
    private org.one.patientmanagement.ui.components.EditableField editableField2;
    private org.one.patientmanagement.ui.components.FillWidthPanel fillWidthPanel1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JPanel infoBoxPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private org.one.patientmanagement.ui.components.PINField pINField1;
    private org.one.patientmanagement.ui.components.PINField pINField2;
    private org.one.patientmanagement.ui.components.StepProgress stepProgress1;
    // End of variables declaration//GEN-END:variables
}
