/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.view;

import org.one.patientmanagement.ui.controller.ControllerBound;
import org.one.patientmanagement.ui.controller.doctor.QueueController;

/**
 *
 * @author KAROL JOHN
 */
public class PatientQueue extends javax.swing.JPanel implements ControllerBound<QueueController> {

    /**
     * Creates new form PatientQueue
     */
    public PatientQueue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        divider = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        headerPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setLayout(new java.awt.BorderLayout(0, 20));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 31)); // NOI18N
        jLabel1.setText("Patient Queue");
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel4.setLayout(new java.awt.BorderLayout(0, 25));

        headerPanel.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel2.setText("jLabel2");
        headerPanel.add(jLabel2, java.awt.BorderLayout.WEST);

        jLabel3.setFont(new java.awt.Font("Manrope SemiBold", 0, 16)); // NOI18N
        jLabel3.setText("jLabel2");
        headerPanel.add(jLabel3, java.awt.BorderLayout.EAST);

        jPanel4.add(headerPanel, java.awt.BorderLayout.PAGE_START);

        jPanel13.setLayout(new java.awt.GridLayout(3, 0, 0, 20));
        jPanel4.add(jPanel13, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jPanel4, gridBagConstraints);

        divider.setBackground(new java.awt.Color(212, 194, 200));
        divider.setPreferredSize(new java.awt.Dimension(1, 100));

        javax.swing.GroupLayout dividerLayout = new javax.swing.GroupLayout(divider);
        divider.setLayout(dividerLayout);
        dividerLayout.setHorizontalGroup(
            dividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        dividerLayout.setVerticalGroup(
            dividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 26, 0, 26);
        jPanel3.add(divider, gridBagConstraints);

        jPanel6.setLayout(new java.awt.BorderLayout(0, 25));

        jPanel14.setLayout(new java.awt.GridLayout(3, 0, 0, 20));
        jPanel6.add(jPanel14, java.awt.BorderLayout.CENTER);

        headerPanel2.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel6.setText("jLabel2");
        headerPanel2.add(jLabel6, java.awt.BorderLayout.WEST);

        jLabel7.setFont(new java.awt.Font("Manrope SemiBold", 0, 16)); // NOI18N
        jLabel7.setText("jLabel2");
        headerPanel2.add(jLabel7, java.awt.BorderLayout.EAST);

        jPanel6.add(headerPanel2, java.awt.BorderLayout.PAGE_START);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jPanel6, gridBagConstraints);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel divider;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel headerPanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setController(QueueController controller) {
        // TODO: set controller
    }
}
