/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.view;

/**
 *
 * @author Lei
 */
public class PatientLogin extends javax.swing.JPanel {

    /**
     * Creates new form ExistingAcctLogin
     */
    public PatientLogin() {
        initComponents();
        
        submitButton.putClientProperty("FlatLaf.style", "arc: 999;");
        
        backdrop.setBadge("Welcome Back");
        backdrop.setHeading("<html><div style='width:400px;'><center>" + "Login your existing account" + "</center></div></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenuItem1 = new javax.swing.JMenuItem();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        stepProgress1 = new org.one.patientmanagement.ui.components.StepProgress();
        jPanel2 = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        formContainer = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Existing_Email = new javax.swing.JLabel();
        Username_Field = new javax.swing.JTextField();
        pINField2 = new org.one.patientmanagement.ui.components.PINField();
        submitButton = new javax.swing.JButton();
        backdrop = new org.one.patientmanagement.ui.components.Backdrop();

        jMenuItem1.setText("jMenuItem1");

        setBackground(new java.awt.Color(255, 248, 248));
        setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane1.setEnabled(false);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(stepProgress1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        formPanel.setBackground(new java.awt.Color(250, 234, 238));
        formPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 70, 70, 70));
        formPanel.setPreferredSize(new java.awt.Dimension(550, 500));
        formPanel.setLayout(new java.awt.BorderLayout(0, 50));

        formContainer.setOpaque(false);
        formContainer.setPreferredSize(new java.awt.Dimension(1166, 300));
        formContainer.setLayout(new java.awt.GridBagLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout(0, 10));

        Existing_Email.setFont(new java.awt.Font("Manrope SemiBold", 0, 20)); // NOI18N
        Existing_Email.setText("Email or Phone Number");
        Existing_Email.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel3.add(Existing_Email, java.awt.BorderLayout.PAGE_START);

        Username_Field.setBackground(new java.awt.Color(255, 240, 244));
        Username_Field.setFont(new java.awt.Font("Manrope", 0, 16)); // NOI18N
        Username_Field.setText("Email / Phone Number");
        Username_Field.setMinimumSize(new java.awt.Dimension(64, 30));
        Username_Field.setName(""); // NOI18N
        Username_Field.setPreferredSize(new java.awt.Dimension(177, 30));
        jPanel3.add(Username_Field, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 284;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 25, 0);
        formContainer.add(jPanel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        formContainer.add(pINField2, gridBagConstraints);

        formPanel.add(formContainer, java.awt.BorderLayout.CENTER);

        submitButton.setBackground(new java.awt.Color(137, 74, 105));
        submitButton.setFont(new java.awt.Font("Manrope SemiBold", 0, 16)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Login");
        submitButton.setPreferredSize(new java.awt.Dimension(95, 55));
        submitButton.addActionListener(this::submitButtonActionPerformed);
        formPanel.add(submitButton, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(formPanel, gridBagConstraints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel1);
        jSplitPane1.setLeftComponent(backdrop);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Existing_Email;
    private javax.swing.JTextField Username_Field;
    private org.one.patientmanagement.ui.components.Backdrop backdrop;
    private javax.swing.JPanel formContainer;
    private javax.swing.JPanel formPanel;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private org.one.patientmanagement.ui.components.PINField pINField2;
    private org.one.patientmanagement.ui.components.StepProgress stepProgress1;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}