/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.view;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author KAROL JOHN
 */
public class PatientView extends javax.swing.JPanel {

    /**
     * Creates new form PatientView
     */
    public PatientView() {
        initComponents();
    }
    
    public CardLayout getNavigationLayout() {
        return (CardLayout) container.getLayout();
    }
    
    public JPanel getNavigationContainer() {
        return container;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        container = new org.one.patientmanagement.ui.components.FillWidthPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        container.setLayout(new java.awt.CardLayout());
        jScrollPane1.setViewportView(container);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.one.patientmanagement.ui.components.FillWidthPanel container;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
