/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.view;

import org.one.patientmanagement.ui.controller.ControllerBound;
import org.one.patientmanagement.ui.controller.patient.PatientStartupController;

/**
 *
 * @author KAROL JOHN
 */
public class PatientStartupView extends javax.swing.JPanel implements ControllerBound<PatientStartupController> {

    private PatientStartupController controller;

    /**
     * Creates new form PatientStartupView
     */
    public PatientStartupView() {
        initComponents();
        
        backdrop1.setHeading("Let’s setup your appointment");

        patientStartupCard1.setInfo("Check in  with your appointment or records.", "Existing Patient");
        patientStartupCard2.setInfo("First time here? Register your details.", "New Patient");

        patientStartupCard1.setImage("/images/existing.png");
        patientStartupCard2.setImage("/images/new.png");

        patientStartupCard1.setButtonAction(l -> {
            controller.onExistingPatient();
        });
        patientStartupCard2.setButtonAction(l -> {
            controller.onNewPatient();
        });

        stepProgress1.removeBack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        stepProgress1 = new org.one.patientmanagement.ui.components.StepProgress();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        patientStartupCard1 = new org.one.patientmanagement.ui.components.PatientStartupCard();
        patientStartupCard2 = new org.one.patientmanagement.ui.components.PatientStartupCard();
        jLabel2 = new javax.swing.JLabel();
        backdrop1 = new org.one.patientmanagement.ui.components.Backdrop();

        setBackground(new java.awt.Color(255, 248, 248));
        setOpaque(false);
        setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane1.setDividerLocation(500);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setResizeWeight(0.1);
        jSplitPane1.setEnabled(false);
        jSplitPane1.setOpaque(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(stepProgress1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 31)); // NOI18N
        jLabel1.setText("How can we help you today?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel2.add(jLabel1, gridBagConstraints);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        patientStartupCard1.setMaximumSize(new java.awt.Dimension(270, 400));
        patientStartupCard1.setMinimumSize(new java.awt.Dimension(270, 400));
        patientStartupCard1.setName(""); // NOI18N
        patientStartupCard1.setPreferredSize(new java.awt.Dimension(270, 400));
        jPanel3.add(patientStartupCard1);
        jPanel3.add(patientStartupCard2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(39, 0, 39, 0);
        jPanel2.add(jPanel3, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Manrope Medium", 0, 16)); // NOI18N
        jLabel2.setText("Need help? Ask our staff for assistance.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel2, gridBagConstraints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel1);
        jSplitPane1.setLeftComponent(backdrop1);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.one.patientmanagement.ui.components.Backdrop backdrop1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private org.one.patientmanagement.ui.components.PatientStartupCard patientStartupCard1;
    private org.one.patientmanagement.ui.components.PatientStartupCard patientStartupCard2;
    private org.one.patientmanagement.ui.components.StepProgress stepProgress1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setController(PatientStartupController controller) {
        this.controller = controller;
    }
}
