/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.plaf.basic.BasicButtonUI;
import org.one.patientmanagement.ui.controller.ControllerBound;
import org.one.patientmanagement.ui.controller.patient.PatientServiceSelectionController;
import org.one.patientmanagement.ui.model.PatientViewModel;

/**
 *
 * @author KAROL JOHN
 */
public class ServiceSelectionView extends javax.swing.JPanel implements ControllerBound<PatientServiceSelectionController> {

    private PatientServiceSelectionController controller;
    private JComponent selectedButton;
    private final Map<PatientViewModel.ServiceSelection, JButton> buttonMap = new HashMap<>();

    /**
     * Creates new form ServiceSelectionView
     */
    public ServiceSelectionView() {
        initComponents();

        cancelButton.putClientProperty("FlatLaf.style", "arc: 999;");
        continueButton1.putClientProperty("FlatLaf.style", "arc: 999;");

        for (var service : PatientViewModel.ServiceSelection.values()) {
            var btn = new JButton();

            btn.setContentAreaFilled(false);
            btn.setOpaque(false);
            btn.setBorderPainted(false);

            btn.setFont(new java.awt.Font("Manrope Medium", 0, 20));
            btn.setForeground(new java.awt.Color(114, 87, 98));
            btn.setText(service.getName());
            btn.setPreferredSize(new java.awt.Dimension(530, 65));

            btn.setUI(new BasicButtonUI() {
                @Override
                public void paint(Graphics g, JComponent c) {
                    Graphics2D g2 = (Graphics2D) g.create();

                    if (c == selectedButton) {
                        g2.setColor(Color.decode("#725762"));
                    } else {
                        g2.setColor(new java.awt.Color(250, 234, 238));
                    }

                    g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 10, 10);

                    g2.dispose();
                    super.paint(g, c);
                }
            });

            btn.addActionListener(l -> {
                controller.setServiceSelection(service);
                setSelection(service);
            });

            buttonMap.put(service, btn);

            selectionPanel.add(btn);
        }
    }

    public void setSelection(PatientViewModel.ServiceSelection service) {
        JButton btn = buttonMap.get(service);
        if (btn != null) {
            selectedButton = btn;
            repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        stepProgress1 = new org.one.patientmanagement.ui.components.StepProgress();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        selectionPanel = new javax.swing.JPanel();
        generalSelection = new javax.swing.JButton();
        pediatricsSelection = new javax.swing.JButton();
        counselingSelection = new javax.swing.JButton();
        examinationSelection = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        continueButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(0, 507));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jPanel3.setMaximumSize(new java.awt.Dimension(800, 2147483647));
        jPanel3.setMinimumSize(new java.awt.Dimension(800, 507));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 690));
        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(stepProgress1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 31)); // NOI18N
        jLabel1.setText("Select a service");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jLabel1, gridBagConstraints);

        selectionPanel.setLayout(new java.awt.GridLayout(4, 0, 0, 10));

        generalSelection.setBackground(new java.awt.Color(114, 87, 98));
        generalSelection.setFont(new java.awt.Font("Manrope Medium", 0, 20)); // NOI18N
        generalSelection.setForeground(new java.awt.Color(255, 255, 255));
        generalSelection.setText("General Checkup");
        generalSelection.setPreferredSize(new java.awt.Dimension(530, 65));
        selectionPanel.add(generalSelection);

        pediatricsSelection.setBackground(new java.awt.Color(250, 234, 238));
        pediatricsSelection.setFont(new java.awt.Font("Manrope Medium", 0, 20)); // NOI18N
        pediatricsSelection.setForeground(new java.awt.Color(114, 87, 98));
        pediatricsSelection.setText("Pediatrics");
        pediatricsSelection.setPreferredSize(new java.awt.Dimension(530, 65));
        selectionPanel.add(pediatricsSelection);

        counselingSelection.setBackground(new java.awt.Color(250, 234, 238));
        counselingSelection.setFont(new java.awt.Font("Manrope Medium", 0, 20)); // NOI18N
        counselingSelection.setForeground(new java.awt.Color(114, 87, 98));
        counselingSelection.setText("Conseling");
        counselingSelection.setPreferredSize(new java.awt.Dimension(530, 65));
        selectionPanel.add(counselingSelection);

        examinationSelection.setBackground(new java.awt.Color(250, 234, 238));
        examinationSelection.setFont(new java.awt.Font("Manrope Medium", 0, 20)); // NOI18N
        examinationSelection.setForeground(new java.awt.Color(114, 87, 98));
        examinationSelection.setText("Physical/Medical Examination");
        examinationSelection.setPreferredSize(new java.awt.Dimension(530, 65));
        selectionPanel.add(examinationSelection);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(31, 0, 103, 0);
        jPanel1.add(selectionPanel, gridBagConstraints);

        cancelButton.setBackground(new java.awt.Color(137, 74, 105));
        cancelButton.setFont(new java.awt.Font("Manrope SemiBold", 0, 16)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(114, 87, 98));
        cancelButton.setText("Cancel the setup");
        cancelButton.setContentAreaFilled(false);
        cancelButton.setPreferredSize(new java.awt.Dimension(400, 50));
        cancelButton.addActionListener(this::cancelButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel1.add(cancelButton, gridBagConstraints);

        continueButton1.setBackground(new java.awt.Color(137, 74, 105));
        continueButton1.setFont(new java.awt.Font("Manrope SemiBold", 0, 16)); // NOI18N
        continueButton1.setForeground(new java.awt.Color(255, 255, 255));
        continueButton1.setText("Continue");
        continueButton1.setPreferredSize(new java.awt.Dimension(400, 50));
        continueButton1.addActionListener(this::continueButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(continueButton1, gridBagConstraints);

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void continueButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continueButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton continueButton1;
    private javax.swing.JButton counselingSelection;
    private javax.swing.JButton examinationSelection;
    private javax.swing.JButton generalSelection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton pediatricsSelection;
    private javax.swing.JPanel selectionPanel;
    private org.one.patientmanagement.ui.components.StepProgress stepProgress1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setController(PatientServiceSelectionController controller) {
        this.controller = controller;
        
        controller.attachToStepProgressController(stepProgress1);
    }
}
