/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.one.patientmanagement.ui;

import com.google.inject.Inject;
import com.google.inject.Provider;
import org.one.patientmanagement.ui.controller.doctor.DashboardController;
import org.one.patientmanagement.ui.controller.doctor.PatientRecordsController;
import org.one.patientmanagement.ui.controller.doctor.QueueController;
import org.one.patientmanagement.ui.controller.navigation.doctor.DoctorNavigator;
import org.one.patientmanagement.ui.controller.navigation.doctor.DoctorRoute;
import org.one.patientmanagement.ui.view.DoctorView;

/**
 *
 * @author KAROL JOHN
 */
public class DoctorFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DoctorFrame.class.getName());

    /**
     * Creates new form DoctorFrame
     */
    @Inject
    public DoctorFrame(DoctorView view, DoctorNavigator navigator,
            Provider<DashboardController> dashboardController,
            Provider<QueueController> queueController,
            Provider<PatientRecordsController> patientRecordsController
    ) {
        initComponents();

        navigator.register(DoctorRoute.DASHBOARD, dashboardController);
        navigator.register(DoctorRoute.QUEUE, queueController);
        navigator.register(DoctorRoute.RECORDS, patientRecordsController);
        
        navigator.goTo(DoctorRoute.DASHBOARD); // first page

        view.getNavigationSidebar().setNavigator(navigator);

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(view);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
