/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui;

/**
 *
 * @author Lei
 */
public class PatientSetup extends javax.swing.JPanel {

    /**
     * Creates new form New_Acct_Scheduling
     */
    public PatientSetup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel15 = new javax.swing.JPanel();
        stepProgress1 = new org.one.patientmanagement.ui.components.StepProgress();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fillWidthPanel1 = new org.one.patientmanagement.ui.components.FillWidthPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        todaySchedule1 = new org.one.patientmanagement.ui.components.TodaySchedule();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        dayOfWeekCard3 = new org.one.patientmanagement.ui.components.DayOfWeekCard();
        dayOfWeekCard4 = new org.one.patientmanagement.ui.components.DayOfWeekCard();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        takePhoto1 = new org.one.patientmanagement.ui.components.TakePhoto();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        textField2 = new org.one.patientmanagement.ui.components.TextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        jPanel10 = new javax.swing.JPanel();
        textField1 = new org.one.patientmanagement.ui.components.TextField();
        textField3 = new org.one.patientmanagement.ui.components.TextField();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        fillWidthPanel2 = new org.one.patientmanagement.ui.components.FillWidthPanel();
        textField4 = new org.one.patientmanagement.ui.components.TextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        textField5 = new org.one.patientmanagement.ui.components.TextField();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        textField6 = new org.one.patientmanagement.ui.components.TextField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        textField7 = new org.one.patientmanagement.ui.components.TextField();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        textField8 = new org.one.patientmanagement.ui.components.TextField();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 248, 248));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setLayout(new java.awt.BorderLayout());

        jPanel15.setOpaque(false);
        jPanel15.setLayout(new java.awt.GridBagLayout());

        stepProgress1.setMaximumSize(new java.awt.Dimension(162, 32803));
        stepProgress1.setName(""); // NOI18N
        stepProgress1.setPreferredSize(new java.awt.Dimension(162, 108));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 600;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        jPanel15.add(stepProgress1, gridBagConstraints);

        add(jPanel15, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 30, 0, 30));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 240, 244));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        jPanel3.setMaximumSize(new java.awt.Dimension(2147483647, 115));
        jPanel3.setMinimumSize(new java.awt.Dimension(460, 300));
        jPanel3.setPreferredSize(new java.awt.Dimension(1250, 300));
        jPanel3.setLayout(new java.awt.BorderLayout(40, 0));

        jPanel6.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout fillWidthPanel1Layout = new javax.swing.GroupLayout(fillWidthPanel1);
        fillWidthPanel1.setLayout(fillWidthPanel1Layout);
        fillWidthPanel1Layout.setHorizontalGroup(
            fillWidthPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );
        fillWidthPanel1Layout.setVerticalGroup(
            fillWidthPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(fillWidthPanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel6.add(jScrollPane1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel2.setText("Select a Doctor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        jPanel6.add(jLabel2, gridBagConstraints);

        jPanel8.setBackground(new java.awt.Color(255, 219, 199));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setFont(new java.awt.Font("Manrope Medium", 0, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("jLabel3");
        jPanel8.add(jLabel3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        jPanel6.add(jPanel8, gridBagConstraints);

        jPanel3.add(jPanel6, java.awt.BorderLayout.EAST);

        jPanel7.setLayout(new java.awt.BorderLayout(0, 10));
        jPanel7.add(todaySchedule1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 25)); // NOI18N
        jLabel1.setText("Select a day");
        jPanel7.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 12, 0);
        jPanel2.add(jPanel3, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(255, 240, 244));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        jPanel4.setLayout(new java.awt.BorderLayout(0, 20));

        jLabel5.setFont(new java.awt.Font("Manrope", 0, 10)); // NOI18N
        jLabel5.setText("<html>Avail on the time that you are able to walk into the clinic. Failure to attend the appointment before the desired time ends will have the entire appointment be discarded.</html>\n");
        jPanel4.add(jLabel5, java.awt.BorderLayout.PAGE_END);

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.GridLayout(1, 0, 16, 0));
        jPanel9.add(dayOfWeekCard3);
        jPanel9.add(dayOfWeekCard4);

        jPanel4.add(jPanel9, java.awt.BorderLayout.CENTER);

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 25)); // NOI18N
        jLabel6.setText("Select a time of day");
        jPanel4.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 12);
        jPanel2.add(jPanel4, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(255, 240, 244));
        jPanel5.setLayout(new java.awt.BorderLayout(0, 20));

        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.GridLayout(1, 0, 25, 20));

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.Y_AXIS));

        jPanel14.setMaximumSize(new java.awt.Dimension(32767, 39));
        jPanel14.setOpaque(false);
        jPanel14.setLayout(new java.awt.GridLayout());

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 25)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Select a time of day");
        jPanel14.add(jLabel4);

        jPanel12.add(jPanel14);
        jPanel12.add(filler8);

        takePhoto1.setMaximumSize(new java.awt.Dimension(2147483647, 120));
        takePhoto1.setMinimumSize(new java.awt.Dimension(149, 120));
        takePhoto1.setOpaque(false);
        jPanel12.add(takePhoto1);
        jPanel12.add(filler1);

        textField2.setMaximumSize(new java.awt.Dimension(2147483647, 75));
        textField2.setMinimumSize(new java.awt.Dimension(64, 75));
        textField2.setName(""); // NOI18N
        textField2.setPreferredSize(new java.awt.Dimension(92, 75));
        jPanel12.add(textField2);
        jPanel12.add(filler2);

        jPanel10.setMaximumSize(new java.awt.Dimension(32767, 75));
        jPanel10.setMinimumSize(new java.awt.Dimension(64, 75));
        jPanel10.setName(""); // NOI18N
        jPanel10.setPreferredSize(new java.awt.Dimension(64, 75));
        jPanel10.setLayout(new java.awt.GridLayout(1, 0, 15, 0));
        jPanel10.add(textField1);
        jPanel10.add(textField3);

        jPanel12.add(jPanel10);

        jPanel11.add(jPanel12);

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new java.awt.BorderLayout());

        fillWidthPanel2.setLayout(new javax.swing.BoxLayout(fillWidthPanel2, javax.swing.BoxLayout.Y_AXIS));

        textField4.setMaximumSize(new java.awt.Dimension(2147483647, 75));
        textField4.setMinimumSize(new java.awt.Dimension(64, 75));
        textField4.setName(""); // NOI18N
        textField4.setPreferredSize(new java.awt.Dimension(92, 75));
        fillWidthPanel2.add(textField4);
        fillWidthPanel2.add(filler3);

        textField5.setMaximumSize(new java.awt.Dimension(2147483647, 75));
        textField5.setMinimumSize(new java.awt.Dimension(64, 75));
        textField5.setName(""); // NOI18N
        textField5.setPreferredSize(new java.awt.Dimension(92, 75));
        fillWidthPanel2.add(textField5);
        fillWidthPanel2.add(filler4);

        textField6.setMaximumSize(new java.awt.Dimension(2147483647, 75));
        textField6.setMinimumSize(new java.awt.Dimension(64, 75));
        textField6.setName(""); // NOI18N
        textField6.setPreferredSize(new java.awt.Dimension(92, 75));
        fillWidthPanel2.add(textField6);
        fillWidthPanel2.add(filler5);

        textField7.setMaximumSize(new java.awt.Dimension(2147483647, 75));
        textField7.setMinimumSize(new java.awt.Dimension(64, 75));
        textField7.setName(""); // NOI18N
        textField7.setPreferredSize(new java.awt.Dimension(92, 75));
        fillWidthPanel2.add(textField7);
        fillWidthPanel2.add(filler6);

        textField8.setMaximumSize(new java.awt.Dimension(2147483647, 75));
        textField8.setMinimumSize(new java.awt.Dimension(64, 75));
        textField8.setName(""); // NOI18N
        textField8.setPreferredSize(new java.awt.Dimension(92, 75));
        fillWidthPanel2.add(textField8);
        fillWidthPanel2.add(filler7);

        jScrollPane3.setViewportView(fillWidthPanel2);

        jPanel13.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel13);

        jPanel5.add(jPanel11, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jPanel5, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setOpaque(false);

        jButton1.setFont(new java.awt.Font("Manrope SemiBold", 0, 16)); // NOI18N
        jButton1.setText("Continue");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(976, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.one.patientmanagement.ui.components.DayOfWeekCard dayOfWeekCard3;
    private org.one.patientmanagement.ui.components.DayOfWeekCard dayOfWeekCard4;
    private org.one.patientmanagement.ui.components.FillWidthPanel fillWidthPanel1;
    private org.one.patientmanagement.ui.components.FillWidthPanel fillWidthPanel2;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private org.one.patientmanagement.ui.components.StepProgress stepProgress1;
    private org.one.patientmanagement.ui.components.TakePhoto takePhoto1;
    private org.one.patientmanagement.ui.components.TextField textField1;
    private org.one.patientmanagement.ui.components.TextField textField2;
    private org.one.patientmanagement.ui.components.TextField textField3;
    private org.one.patientmanagement.ui.components.TextField textField4;
    private org.one.patientmanagement.ui.components.TextField textField5;
    private org.one.patientmanagement.ui.components.TextField textField6;
    private org.one.patientmanagement.ui.components.TextField textField7;
    private org.one.patientmanagement.ui.components.TextField textField8;
    private org.one.patientmanagement.ui.components.TodaySchedule todaySchedule1;
    // End of variables declaration//GEN-END:variables
}
