/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.one.patientmanagement.ui;

import com.google.inject.Inject;
import com.google.inject.Provider;
import org.one.patientmanagement.ui.controller.navigation.patient.flow.PatientRoute;
import org.one.patientmanagement.ui.controller.navigation.patient.PatientFlowNavigator;
import org.one.patientmanagement.ui.controller.navigation.patient.flow.step.StartupStep;
import org.one.patientmanagement.ui.controller.patient.PatientDashboardController;
import org.one.patientmanagement.ui.controller.patient.PatientLoginController;
import org.one.patientmanagement.ui.controller.patient.PatientServiceSelectionController;
import org.one.patientmanagement.ui.controller.patient.PatientSetupController;
import org.one.patientmanagement.ui.controller.patient.PatientSignupController;
import org.one.patientmanagement.ui.controller.patient.PatientStartupController;
import org.one.patientmanagement.ui.view.PatientView;

/**
 *
 * @author KAROL JOHN
 */
public class PatientFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PatientFrame.class.getName());

    /**
     * Creates new form PatientFrame
     */
    @Inject
    public PatientFrame(
            Provider<PatientDashboardController> patientDashboardControllerProvider,
            Provider<PatientLoginController> patientLoginControllerProvider,
            Provider<PatientServiceSelectionController> patientServiceSelectionControllerProvider,
            Provider<PatientSignupController> patientSignupControllerProvider,
            Provider<PatientSetupController> patientSetupControllerProvider,
            Provider<PatientStartupController> patientStartupControllerProvider,
            PatientView view,
            PatientFlowNavigator navigator
    ) {
        initComponents();

        navigator.register(PatientRoute.STARTUP, patientStartupControllerProvider);
        navigator.register(PatientRoute.LOGIN, patientLoginControllerProvider);
        navigator.register(PatientRoute.SIGN_UP, patientSignupControllerProvider);
        navigator.register(PatientRoute.SETUP, patientSetupControllerProvider);
        navigator.register(PatientRoute.SELECTION, patientServiceSelectionControllerProvider);
        navigator.register(PatientRoute.DASHBOARD, patientDashboardControllerProvider);
        
        navigator.start(new StartupStep());

        getContentPane().add(view);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient View");
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new java.awt.GridLayout());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
