/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.one.patientmanagement.ui.view.dialog;

import com.google.inject.assistedinject.Assisted;
import com.google.inject.assistedinject.AssistedInject;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import org.one.patientmanagement.ui.controller.ControllerBound;
import org.one.patientmanagement.ui.controller.doctor.DoctorPatientDashboardController;
import org.one.patientmanagement.ui.controller.doctor.DoctorPatientDashboardDialogController;
import org.one.patientmanagement.ui.view.DoctorPatientDashboard;

/**
 *
 * @author KAROL JOHN
 */
public class DoctorPatientDashboardDialog extends javax.swing.JDialog implements ControllerBound<DoctorPatientDashboardDialogController> {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DoctorPatientDashboardDialog.class.getName());
    private DoctorPatientDashboardDialogController controller;
    private final DoctorPatientDashboard view;

    /**
     * Creates new form DoctorPatientDashboardDialog
     */
    @AssistedInject
    public DoctorPatientDashboardDialog(
            @Assisted java.awt.Window parent,
            DoctorPatientDashboard view) {

        super((JFrame) parent, true);
        initComponents();

        this.view = view;
        getContentPane().add(view, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void setController(DoctorPatientDashboardDialogController controller) {
        this.controller = controller;
    }

    public DoctorPatientDashboardController getViewController() {
        return view.getController();
    }
}
